### ISSUE TITLE
Update QuickStart doc.

### ISSUE THREAD

**Issue by NicolasRouquette** [TheoBourdais/ComputationalHypergraphDiscovery#2]
The API in the QuickStart example is out of date:
https://github.com/TheoBourdais/ComputationalHypergraphDiscovery/blob/5cfe4349119ea8ee58dcce336f75959e3996b294/src/ComputationalHypergraphDiscovery/_GraphDiscoveryMain.py#L73

It seems that the example should be updated like this:

```python
kernels=CHD.Modes.LinearMode()+CHD.Modes.QuadraticMode()
graph_discovery = CHD.GraphDiscovery.from_dataframe(df,mode_kernels=kernels)
```

**Comment by TheoBourdais** [comment]
Thank you for pointing this out, this is fixed.
