### ISSUE TITLE
Error in `prune_ancestors`: ValueError "Need at least one array to stack"

### ISSUE THREAD

**Issue by Alexey-Voronin** [TheoBourdais/ComputationalHypergraphDiscovery#6]
I encountered a `ValueError` when trying to fit a model using the `GraphDiscovery` class from the `ComputationalHypergraphDiscovery` library. This error occurred when calling the `fit()` method. The error message indicates that there is an issue with the `np.stack` function, which expects at least one array to stack but received none.

### Steps to Reproduce
Here is a minimal example to reproduce the error:

```python
import ComputationalHypergraphDiscovery as chd
import numpy as np
import pandas as pd

num_rows = 100  # Adjust number of rows
rand_arr0 = np.random.rand(num_rows)
rand_arr1 = np.random.rand(num_rows)

# Example 1 (works fine)
df = pd.DataFrame({
    'Column_1': rand_arr0,
    'Column_2': rand_arr1,
})
df = df.sample(n=df.shape[0]//2, random_state=1)

graph_discovery = chd.GraphDiscovery.from_dataframe(df)
graph_discovery.fit()
graph_discovery.plot_graph()

# Example 2 (almost identical to example 1 but errors out)
df = pd.DataFrame({
    'Column_1': rand_arr0,
    'Column_2': 5*rand_arr0+1,
})
df = df.sample(n=df.shape[0]//2, random_state=1)

graph_discovery = chd.GraphDiscovery.from_dataframe(df)
graph_discovery.fit()
graph_discovery.plot_graph()
```

### Expected Behavior
I expected the `GraphDiscovery.fit()` function to process the DataFrame without throwing an error.

### Observed Behavior
The execution failed on second example with the following traceback:
```python
Finding ancestors with kernel [linear]: 0it [00:00, ?it/s]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 23
     19 df = df.sample(n=df.shape[0]//2,random_state=1).copy()
     22 graph_discovery=chd.GraphDiscovery.from_dataframe(df)
---> 23 graph_discovery.fit()
     24 graph_discovery.plot_graph()

File ~/repos/test/lib/python3.12/site-packages/ComputationalHypergraphDiscovery/_GraphDiscoveryMain.py:298, in GraphDiscovery.fit(self, targets, key, kernel_chooser, mode_chooser, message)
    287 if not np.any(mask_kernel):
    288     continue
    290 (
    291     active_modess_kernel,
    292     noisess_kernel,
    293     Z_lows_kernel,
    294     Z_highs_kernel,
    295     activationss_kernel,
    296     gammas_kernel,
    297     ybs_kernel,
--> 298 ) = self.prune_ancestors(
    299     kernel,
    300     self.ancestor_finding_step_funcs,
    301     X=self.X,
    302     active_modess_kernel=active_modess[mask_kernel],
    303     gas_kernel=gas[mask_kernel],
    304     ybs_kernel=ybs[mask_kernel],
    305     gammas_kernel=gammas[mask_kernel],
    306     subkeys_kernel=subkeys[mask_kernel],
    307     noise_kernel=noisess[mask_kernel],
    308     Z_low_kernel=Z_lows[mask_kernel],
    309     Z_high_kernel=Z_highs[mask_kernel],
    310     loop_number=len(self.modes.clusters) - 2,
    311     message=message,
    312 )
    313 anomaly_noise = np.logical_or(noisess_kernel > 1.05, noisess_kernel < -0.05)
    314 anomaly_Z_low = np.logical_or(Z_lows_kernel > 1.05, Z_lows_kernel < -0.05)

File ~/repos/test/lib/python3.12/site-packages/ComputationalHypergraphDiscovery/_GraphDiscoveryMain.py:631, in GraphDiscovery.prune_ancestors(self, kernel, ancestor_finding_step_funcs, X, active_modess_kernel, gas_kernel, ybs_kernel, gammas_kernel, subkeys_kernel, noise_kernel, Z_low_kernel, Z_high_kernel, loop_number, message)
    624         break
    625 pbar.close()
    626 return (
    627     np.stack(ancestor_modess, axis=1),
    628     np.stack(noisess_kernel, axis=1),
    629     np.stack(Z_lows_kernel, axis=1),
    630     np.stack(Z_highs_kernel, axis=1),
--> 631     np.stack(activationss_kernel, axis=1),
    632     np.stack(gammas, axis=1),
    633     np.stack(ybs, axis=1),
    634 )

File ~/repos/test/lib/python3.12/site-packages/jax/_src/numpy/lax_numpy.py:2828, in stack(arrays, axis, out, dtype)
   2824 @util.implements(np.stack, skip_params=['out'])
   2825 def stack(arrays: np.ndarray | Array | Sequence[ArrayLike],
   2826           axis: int = 0, out: None = None, dtype: DTypeLike | None = None) -> Array:
   2827   if not len(arrays):
-> 2828     raise ValueError("Need at least one array to stack.")
   2829   if out is not None:
   2830     raise NotImplementedError("The 'out' argument to jnp.stack is not supported.")

ValueError: Need at least one array to stack.
```

### Environment
- ComputationalHypergraphDiscovery version: latest commit 
- Python version: 3.12.4
- Operating System: MacOS

### Additional Context

I am investigating the Computational Hypergraph Discovery (CHD) mechanisms by applying it to small graphs. There is a noticeable difference in execution paths between Example 1 and Example 2. Specifically, Example 1 does not trigger the `prune_ancestors` method, unlike Example 2. This divergence stems from the kernel selection process in `GraphDiscovery.choose_kernel`: Example 1 results in `chosen_kernels=[-1,-1]`, suggesting no kernel was chosen, while Example 2 consistently selects a kernel with `chosen_kernels=[0,0]`, which initiates the call to `prune_ancestors`.

The error within `prune_ancestors` is linked to the `activationss_kernel` list, which is empty (`len(activationss_kernel)=0`), in contrast to other lists in the return statement, each containing one element. This inconsistency causes a `ValueError` because the `np.stack` function requires at least one non-empty array to function correctly.

I would appreciate some guidance on getting these issues resolved for small examples.

**Comment by TheoBourdais** [comment]
Hi Alexey, 

Thank you for catching this issue! You tried an edge case I had never tried before, two nodes in the graph. The activation computation for one step is done during the next pruning. Since there is only one ancestor here, there was no pruning to do! 
I added the edge cases in `prune_ancestors` in the commit c7748f7. 

Let me know if the error is still there. 

#

**Comment by Alexey-Voronin** [comment]
The fix works. Thank you!
